name: Projectized.co
favicon: null
layout_spectrum: 1
typography_spectrum: 1
title: Projectized.co
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-80513059-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#595959'
    - '#969696'
    - '#0f89eb'
    - '#000000'
  brandStrength: 1
  lightness: 0.625
  saturation: 0.5625
  rhythmicContrast: 0
purpose: []
