typography_spectrum: 1
color:
  brandColors:
    - '#ffffff'
    - '#595959'
    - '#969696'
    - '#0f89eb'
    - '#000000'
  brandStrength: 1
  lightness: 0.75
  saturation: 0.125
  rhythmicContrast: 0
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.63331
analytics:
  google: UA-80513059-1
  facebook: null
  twitter: null
author:
  name: Moemen Fouad
  email: moemen@projectized.co
  url: projectized.co
name: Projectized.co
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - id: c30a1f44-6194-41d8-bc83-73cea387dc5c
    url: 2016-07-08-think-smarterthink-projectized.html
    name: Home
    type: content
favicon: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: Projectized.co
purpose: []
