title: Projectized.co
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
color:
  saturation: 0.125
  brandStrength: 1
  lightness: 0.75
  brandColors:
    - '#2E3192'
    - '#1C1E59'
    - '#030309'
    - '#C81F30'
    - '#6E101B'
  rhythmicContrast: 0
cta:
  bucket: null
  version: null
  domain: null
navigation: []
favicon: null
name: Projectized.co
author:
  name: ''
  email: ''
  url: ''
opengraph:
  image: null
  type: null
  appId: null
analytics:
  twitter: '#Projectized.co'
  google: UA-80513059-1
  facebook: null
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/f1111b68-8fae-49b1-8eb7-9d3333f3cc27.png
typography_spectrum: 1
layout_spectrum: 0.63331
