name: Projectized.co
favicon: null
layout_spectrum: 0.2293907
typography_spectrum: 1
title: Projectized.co
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#262262'
    - '#bf1e2e'
    - '#00aeef'
    - '#9494b5'
    - '#ffffff'
  brandStrength: 0.5
  lightness: 0.6875
  saturation: 0.5625
  rhythmicContrast: 0.5
purpose: []
