title: Projectized.co
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
description: Taking Business Forward
color:
  saturation: 0.125
  brandStrength: 1
  rhythmicContrast: 0
  brandColors:
    - '#2E3192'
    - '#1C1E59'
    - '#030309'
    - '#C81F30'
    - '#6E101B'
  lightness: 0.75
navigation:
  - name: Services
    id: 91c4161b-6ae5-426c-b0b9-947b21478a90
    type: content
  - name: Home
    id: c30a1f44-6194-41d8-bc83-73cea387dc5c
    type: content
  - name: 'Vision, Mission, & Core Values'
    id: 10689ad2-0e1f-40ce-aa05-ebd454f1b41e
    type: content
  - name: About Us
    id: af3b9928-fe37-4eab-9846-ca5e0d71f825
    type: content
  - name: Linkedin
    url: >-
      https://www.linkedin.com/company/10684341?trk=tyah&trkInfo=clickedVertical%3Acompany%2CclickedEntityId%3A10684341%2Cidx%3A1-1-1%2CtarId%3A1469361573377%2Ctas%3Aprojectized
    type: external
  - name: Contact Us
    id: d1f339a2-2875-477c-84c5-0d43cb067993
    type: content
cta:
  bucket: null
  version: null
  domain: null
name: Projectized.co
author:
  name: ''
  email: ''
  url: ''
favicon: null
opengraph:
  image: null
  type: null
  appId: null
analytics:
  twitter: '#Projectized.co'
  google: UA-80513059-1
  facebook: null
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/f1111b68-8fae-49b1-8eb7-9d3333f3cc27.png
typography_spectrum: 0.8351254
layout_spectrum: 0.63331
