name: Projectized
favicon: null
layout_spectrum: 0.74977
typography_spectrum: 1
title: Projectized Solutions
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#89d4f4'
    - '#172645'
    - '#019ec7'
    - '#00d2f5'
  brandStrength: 0.75
  lightness: 0.5625
  saturation: 0.5221817314159125
  rhythmicContrast: 0.75
purpose: []
