typography_spectrum: 1
color:
  saturation: 0.125
  brandStrength: 1
  lightness: 0.75
  brandColors:
    - '#2E3192'
    - '#1C1E59'
    - '#030309'
    - '#C81F30'
    - '#6E101B'
  rhythmicContrast: 0
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.63331
analytics:
  twitter: '#Projectized.co'
  google: UA-80513059-1
  facebook: null
author:
  name: ''
  email: ''
  url: ''
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/f1111b68-8fae-49b1-8eb7-9d3333f3cc27.png
name: Projectized.co
cta:
  bucket: null
  version: null
  domain: null
navigation:
  - id: c30a1f44-6194-41d8-bc83-73cea387dc5c
    url: 2016-07-08-think-smarterthink-projectized.html
    name: Home
    type: content
  - id: >-
      https://www.linkedin.com/company/10684341?trk=tyah&trkInfo=clickedVertical%3Acompany%2CclickedEntityId%3A10684341%2Cidx%3A1-1-1%2CtarId%3A1469361573377%2Ctas%3Aprojectized
    url: >-
      https://www.linkedin.com/company/10684341?trk=tyah&trkInfo=clickedVertical%3Acompany%2CclickedEntityId%3A10684341%2Cidx%3A1-1-1%2CtarId%3A1469361573377%2Ctas%3Aprojectized
    name: Linkedin
    type: external
  - id: c6bc708d-5e44-4b97-ab83-d2e92d2f0ad2
    url: 2016-06-25-contact-us.html
    name: Contact Us
    type: content
  - id: 98c8b3ee-c65b-41d8-b50f-d16978e3b648
    url: 2016-07-15-about-us.html
    name: About Us
    type: content
  - id: aafa5558-f231-404f-bd7d-9514deed8548
    url: 2016-07-04-services.html
    name: Services
    type: content
  - id: 4d3d42cf-1f48-466d-a099-4781ac01207f
    url: 2016-06-15-vision-mission-core-values.html
    name: 'Vision, Mission & Core Values.'
    type: content
favicon: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
title: Projectized.co
purpose: []
